/**
 * GET  /api/agent-home         — all 3 agent skybox homes
 * GET  /api/agent-home?agent=  — single agent home
 * POST /api/agent-home         — generate new home for agent
 */

import { NextRequest, NextResponse } from 'next/server';
import {
  generateAgentHome,
  getAllAgentHomes,
  getRiskLevelFromScore,
  cacheLiveHome,
  type AgentPersonality,
  type RiskLevel,
} from '@/server/blockade-skybox';

export const runtime = 'nodejs';

export async function GET(req: NextRequest) {
  const agent = req.nextUrl.searchParams.get('agent') as AgentPersonality | null;
  const valid: AgentPersonality[] = ['watcher', 'strategist', 'executor'];

  if (agent && !valid.includes(agent)) {
    return NextResponse.json({ error: 'agent must be: watcher | strategist | executor' }, { status: 400 });
  }

  if (agent) {
    const home = await generateAgentHome(agent);
    return NextResponse.json({ bounty: 'Blockade Labs: Solving the Homeless Agent Problem', home });
  }

  const homes = getAllAgentHomes();
  return NextResponse.json({
    bounty: 'Blockade Labs: Solving the Homeless Agent Problem',
    description: 'Every AegisOS agent has a 3D immersive home generated by Skybox AI',
    promoCode: 'ETHDEN26',
    apiSignup: 'https://blockadelabs.com',
    agents: homes,
    mockMode: homes.every((h) => h.mockMode),
  });
}

export async function POST(req: NextRequest) {
  let body: { agent?: string; riskScore?: number; riskLevel?: string };
  try { body = await req.json(); } catch { return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 }); }

  const { agent, riskScore, riskLevel } = body;
  const valid: AgentPersonality[] = ['watcher', 'strategist', 'executor'];

  if (!agent || !valid.includes(agent as AgentPersonality)) {
    return NextResponse.json({ error: 'agent must be: watcher | strategist | executor' }, { status: 400 });
  }

  const level: RiskLevel = (riskLevel as RiskLevel) ??
    (riskScore !== undefined ? getRiskLevelFromScore(riskScore) : 'moderate');

  const home = await generateAgentHome(agent as AgentPersonality, level);
  if (!home.mockMode) cacheLiveHome(home); // cache live results for GET /api/agent-home

  return NextResponse.json({
    bounty: 'Blockade Labs: Solving the Homeless Agent Problem',
    message: `Generated skybox home for ${agent} agent`,
    home,
  });
}
